config/routes.rb
require 'resque_web'

Rails.application.routes.draw do
  resources :turns
  resources :regions
  resources :local_participation_records
  resources :boards
  resources :user

  root 'boards#show'

  match '/auth/:provider/callback', to: 'sessions#create_from_omniauth', via: [:get, :post]
  get '/logout', to: 'sessions#destroy'

  mount ResqueWeb::Engine => '/resque_web'

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :regions
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @turns = Turn.where(board_id: @board.id).order("created_at DESC")
    @lprs = LocalParticipationRecord.where(board_id: @board.id).where("updated_at > ?",Time.now - 1.hours)
    begin
      @creator = User.find_by_id!(@board.user_id).username
    rescue ActiveRecord::RecordNotFound
      @creator = "Anonymous"
    end
    @margin = 2
    @room_width = 40
    @room_height = 40
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      begin
        @board = Board.find_by_id!(params[:id])
      rescue ActiveRecord::RecordNotFound
        @board = Board.find 0
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:user_id, :title, :description, :rooms_positions, :color, :background_image_url, :height, :width)
    end
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rooms_positions %><br>
    <%= f.text_area :rooms_positions %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :background_image_url %><br>
    <%= f.text_field :background_image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boards</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Title</th>
      <th>Description</th>
      <th>Rooms positions</th>
      <th>Color</th>
      <th>Background image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.username %></td>
        <td><%= board.title %></td>
        <td><%= board.description %></td>
        <td><%= board.rooms_positions %></td>
        <td><%= board.color %></td>
        <td><%= board.background_image_url %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>